<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAPhkFu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAPhkFu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAPhkFu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAPhkFu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBAPhkFu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BAPhkFu',
    'container.build_id' => '54373fc7',
    'container.build_time' => 1588073720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAPhkFu');
