<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI0Q0Op0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI0Q0Op0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI0Q0Op0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI0Q0Op0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerI0Q0Op0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'I0Q0Op0',
    'container.build_id' => 'ce9c5d10',
    'container.build_time' => 1588265496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI0Q0Op0');
