<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6NbExNL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6NbExNL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6NbExNL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6NbExNL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6NbExNL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6NbExNL',
    'container.build_id' => '9f25962e',
    'container.build_time' => 1588247202,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6NbExNL');
