<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9662464f.js',
                '/build/0.c8a27c26.js',
                '/build/app.0737effa.js',
            ],
            'css' => [
                '/build/app.99c21d8d.css',
            ],
        ],
    ],
],

]];
